[build]
  command = "npm run build"
  prebuild = "npx playwright install"
  functions = "functions"
  timeout = 30

[functions]
  [functions.cron-job]
  name = "cron-job"
  schedule = "*/15 * * * *"
  path = "cronJob.ts"
